name: ci

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6.0.2

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6.4.0
        with:
          node-version: "24"
          cache: "npm"

      - run: make setup
      - run: make static-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6.0.2

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6.4.0
        with:
          node-version: "24"
          cache: "npm"

      - run: make setup
      - run: make test
